# Utilizando for imprima todos 
# os números pares ate 100
for n in range(2,101,2):
    print(n)
# VAI CAIR NA PROVA VAI CAIR NA PROVA VAI CAIR NA PROVA VAI CAIR NA PROVA VAI CAIR NA PROVA VAI CAIR NA PROVA VAI CAIR NA PROVA VAI CAIR NA PROVA VAI CAIR NA PROVA VAI CAIR NA PROVA 